allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
minimumReleaseAgeExclude:
  - '@prisma/adapter-pg@7.9.0'
  - '@prisma/client-runtime-utils@7.9.0'
  - '@prisma/client@7.9.0'
  - '@prisma/config@7.9.0'
  - '@prisma/debug@7.9.0'
  - '@prisma/driver-adapter-utils@7.9.0'
  - '@prisma/engines@7.9.0'
  - '@prisma/fetch-engine@7.9.0'
  - '@prisma/get-platform@7.9.0'
  - '@typescript-eslint/eslint-plugin@8.65.0 || 8.66.0'
  - '@typescript-eslint/parser@8.65.0 || 8.66.0'
  - '@typescript-eslint/project-service@8.65.0 || 8.66.0'
  - '@typescript-eslint/scope-manager@8.65.0 || 8.66.0'
  - '@typescript-eslint/tsconfig-utils@8.65.0 || 8.66.0'
  - '@typescript-eslint/type-utils@8.65.0 || 8.66.0'
  - '@typescript-eslint/types@8.65.0 || 8.66.0'
  - '@typescript-eslint/typescript-estree@8.65.0 || 8.66.0'
  - '@typescript-eslint/utils@8.65.0 || 8.66.0'
  - '@typescript-eslint/visitor-keys@8.65.0 || 8.66.0'
  - prisma@7.9.0
  - typescript-eslint@8.65.0 || 8.66.0
  - eslint@10.8.0
  - fastify@5.11.2
  - tsx@4.23.5
  - '@googleapis/drive@21.0.0'
