allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
minimumReleaseAgeExclude:
  - '@prisma/adapter-pg@7.9.0'
  - '@prisma/client-runtime-utils@7.9.0'
  - '@prisma/client@7.9.0'
  - '@prisma/config@7.9.0'
  - '@prisma/debug@7.9.0'
  - '@prisma/driver-adapter-utils@7.9.0'
  - '@prisma/engines@7.9.0'
  - '@prisma/fetch-engine@7.9.0'
  - '@prisma/get-platform@7.9.0'
  - prisma@7.9.0
  - fastify@5.11.2
  - tsx@4.23.5
  - '@googleapis/drive@21.0.0'
