-- Feature 47: search text of a movement's description, computed by PostgreSQL.
--
-- Written by hand (not generated by `prisma migrate dev`) because Prisma 7
-- cannot express a GENERATED ... STORED column, the same precedent as the
-- partial dedup index and the NULLS NOT DISTINCT unique index of ADR-011.
-- `lower(translate(...))` is IMMUTABLE, which `unaccent()` is not; the schema
-- declares the column as `descriptionSearch String?` only to be able to filter
-- by it. Nothing in the application may write it: PostgreSQL rejects an INSERT
-- or an UPDATE that mentions a generated column.
--
-- No data is inserted, updated or deleted here: PostgreSQL fills the column for
-- the existing rows as part of the ALTER.

-- AlterTable
ALTER TABLE "Movement" ADD COLUMN "descriptionSearch" TEXT
  GENERATED ALWAYS AS (lower(translate("description",
    'áàäâãéèëêíìïîóòöôõúùüûñçÁÀÄÂÃÉÈËÊÍÌÏÎÓÒÖÔÕÚÙÜÛÑÇ',
    'aaaaaeeeeiiiiooooouuuuncAAAAAEEEEIIIIOOOOOUUUUNC'))) STORED;

-- CreateIndex
CREATE INDEX "Movement_categoryId_idx" ON "Movement"("categoryId");
