/**
 * The HTML reader of THIS bank only (feature 19).
 *
 * The file is called `.xls` and is not an Excel: it is an XHTML page with a
 * single table inside, which is an old and very common trick of Spanish
 * banking. `exceljs` cannot open it — there is no ZIP and no OOXML — so the
 * table is read here, WITHOUT adding a dependency (decision of the human: no
 * `cheerio`, no `node-html-parser`).
 *
 * Why a handful of regular expressions is enough, when "parse HTML with regex"
 * is normally a mistake: this module does NOT interpret a document. It only
 * SLICES one that is generated by a machine, has no nested tables, no
 * JavaScript and no optional closing tags. Everything that does not fit the
 * expected shape is not silently accepted: it ends up in `unparsedRows` or
 * rejects the file for having no recognizable header. And if the day comes when
 * the HTML gets complicated, what changes is the inside of this file — the
 * parser above it does not know how the rows were obtained.
 *
 * It stays inside `modules/openbank/` and does NOT move to `lib/`, exactly like
 * the quoted-CSV reader of the other bank that needed one: `docs/conventions.md`
 * §Parsers de banco shares the SHAPE of the output and the encoding, never the
 * code that reads a format. The next bank that exports HTML copies the pattern,
 * not the module.
 */

/** One `<tr>` of the document, with the text of its cells already clean. */
export interface HtmlRow {
  /**
   * 1-based position of the row inside the document, counting every `<tr>`
   * including the decorative ones. It is what gets reported in `unparsedRows`:
   * the file has no meaningful line numbers (it is written almost entirely on
   * one line), so "row 43 of the table" is the reference a human can actually
   * find when he opens the file.
   */
  row: number
  /** Text of every cell of the row, in order, including the empty ones. */
  cells: string[]
}

const rowPattern = /<tr\b[^>]*>([\s\S]*?)<\/tr>/gi
/** A cell, either self-closed (`<td … />`) or with content. Openbank writes both. */
const cellPattern = /<t[dh]\b[^>]*?\/>|<t[dh]\b[^>]*>([\s\S]*?)<\/t[dh]>/gi
const tagPattern = /<[^>]*>/g

/**
 * Slices the document into its rows and their cells.
 *
 * The inner tags of a cell (`<b>`, `<font>`) are dropped and only their text
 * survives; entities are resolved; whitespace is collapsed and trimmed, so a
 * cell written across several source lines still comes out as one clean value.
 * Rows are returned ALL of them, decorative ones included: deciding what is a
 * movement is the parser's job, not the slicer's.
 */
export function readHtmlTableRows(document: string): HtmlRow[] {
  const rows: HtmlRow[] = []
  for (const match of document.matchAll(rowPattern)) {
    rows.push({ row: rows.length + 1, cells: readCells(match[1]) })
  }
  return rows
}

function readCells(rowHtml: string): string[] {
  return [...rowHtml.matchAll(cellPattern)].map((match) => cleanCellText(match[1] ?? ''))
}

/** Text of a cell: no tags, entities resolved, whitespace collapsed. */
function cleanCellText(html: string): string {
  return decodeEntities(html.replace(tagPattern, '')).replace(/\s+/g, ' ').trim()
}

const namedEntities: Record<string, string> = {
  amp: '&',
  lt: '<',
  gt: '>',
  quot: '"',
  apos: "'",
  nbsp: '\u00a0',
}

/**
 * Resolves the handful of entities this export can carry. The real sample has
 * NONE (the accents travel as cp1252 bytes), but `&amp;` in a concept is one
 * change of the bank away, and `&amp;amp;` reaching the database would be a
 * silent corruption of exactly the kind this project keeps paying for.
 *
 * `&amp;` is resolved LAST, on purpose: doing it first would turn `&amp;lt;`
 * into `<`, which is not what the file said.
 */
function decodeEntities(text: string): string {
  return text
    .replace(/&#(\d+);/g, (_, code: string) => String.fromCodePoint(Number(code)))
    .replace(/&#x([0-9a-f]+);/gi, (_, code: string) =>
      String.fromCodePoint(Number.parseInt(code, 16)),
    )
    .replace(/&(lt|gt|quot|apos|nbsp);/gi, (_, name: string) => namedEntities[name.toLowerCase()])
    .replace(/&amp;/gi, namedEntities.amp)
}

/**
 * The charset the document DECLARES, lowercased, or `null` when it declares
 * none. Both spellings are understood: the `<meta http-equiv="Content-Type">`
 * this bank writes today and the short `<meta charset>` of HTML5.
 *
 * This is the only honest way to tell whether the file arrived in the encoding
 * the bank emits: cp1252 maps all 256 bytes, so a file that turned up in UTF-8
 * would decode without a single error and hand over mojibake (see
 * `src/lib/cp1252.ts`). The criterion is what the file AFFIRMS about itself,
 * never a guess about its bytes.
 */
export function readDeclaredCharset(document: string): string | null {
  const fromContentType = document.match(
    /<meta\b[^>]*http-equiv\s*=\s*["']?content-type["']?[^>]*charset\s*=\s*([\w-]+)/i,
  )
  if (fromContentType) {
    return fromContentType[1].toLowerCase()
  }
  const fromShortForm = document.match(/<meta\b[^>]*\bcharset\s*=\s*["']?([\w-]+)/i)
  return fromShortForm ? fromShortForm[1].toLowerCase() : null
}

/**
 * The content of the HTML comments that appear BEFORE the given tag, in order.
 *
 * Only the comments before the table are looked at (`before` is `'<table'`),
 * which is the same rule the other banks apply to their preamble lines: what
 * the human writes by hand lives ABOVE the bank's own data and is recognized by
 * its label and its position, never by its shape somewhere inside the table.
 */
export function readHtmlComments(document: string, before: string): string[] {
  const limit = document.toLowerCase().indexOf(before.toLowerCase())
  const head = limit === -1 ? document : document.slice(0, limit)
  return [...head.matchAll(/<!--([\s\S]*?)-->/g)].map((match) => match[1].trim())
}
